# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'CampaignSdkReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CampaignSdkReactNative
  pod 'campaign', '0.2.0'

end
